### ISSUE TITLE
Print out trial sequence

### ISSUE THREAD

**Issue by baranan** [minnojs/minno-time#51]
It will be nice if PIP would support a debug mode that prints out anything that happens (actions caught, conditions met) to allow the researcher to understand what's not working in the trial sequence.

**Comment by eladzlot** [comment]
Agreed.
How about: 

* Trial start
* Trial end
* Event triggered (event name)
* Event triggered (interaction + whether all conditions are true for that interaction)

Adding this type of logging will necessarily hit performance.
I'm assuming we will be looking for a kill switch for production (like we have for `skip`).

**Comment by baranan** [comment]
Regarding the first two: Do we need them? 'begin' is an event, and 'end' is an action in an interaction.

Regarding the last one: Do you mean that each time an event is triggered you will also report the evaluation of the conditions of each interaction? That will be very helpful, but indeed a lot of printing. Definitely, we must prevent it from working on production. And, also not show it by default, only if the researcher requests it. 

Would it be printed in the console or also under the canvas? 

Should the researcher turn it on in the manager as another debug level, or specifically in the miTime script?

**Comment by eladzlot** [comment]
Begin and end help frame the information, so that data from different trails do not mix.

I mean something like `INTERACTION(true): {conditions:[...], actions:[...]}`, so that we log only the result of whole conditions.

We'll be printing to the console, right now printing to the screen is too much structural work. Also, we're printing quite a lot here, if we print to the screen users may have a problem interacting with the player while reading the log.

I'm thinking it should be rather focused. At the minno-time level, possibly a the single trial level. I know from experience that this much logging gets confusing pretty fast.

**Comment by baranan** [comment]
Sounds good. Only remember not to provide this by default, and add to the documentation how to turn this on.

**Comment by eladzlot** [comment]
Completed. see docs [here](https://minnojs.github.io/minno-time/0.4/time/API.html#debug).
